# Generated by Django 5.1 on 2024-08-15 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastebin', '0002_textsnippet_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textsnippet',
            name='language',
            field=models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('html', 'HTML'), ('css', 'CSS'), ('plaintext', 'Plain Text')], default='plaintext', max_length=20),
        ),
    ]
